export const CHAT_CURRENT_SET = "CHAT_CURRENT_SET" 
export const CHAT_CURRENT_RESET = "CHAT_CURRENT_SET_RESET"

export const CHAT_ALL_LIST_REQUEST = "CHAT_ALL_LIST_REQUEST"
export const CHAT_ALL_LIST_SUCCESS = "CHAT_ALL_LIST_SUCCESS"
export const CHAT_ALL_LIST_FAIL = "CHAT_ALL_LIST_FAIL"
export const CHAT_ALL_LIST_RESET = "CHAT_ALL_LIST_RESET"

export const CHAT_ONETOONE_CREATE_REQUEST =  "CHAT_ONETOONE_CREATE_REQUEST"
export const CHAT_ONETOONE_CREATE_SUCCESS =  "CHAT_ONETOONE_CREATE_SUCCESS"
export const CHAT_ONETOONE_CREATE_FAIL =  "CHAT_ONETOONE_CREATE_FAIL"
export const CHAT_ONETOONE_CREATE_RESET = "CHAT_ONETOONE_CREATE_RESET"

export const CHAT_ONETOONE_LIST_REQUEST =  "CHAT_ONETOONE_LIST_REQUEST"
export const CHAT_ONETOONE_LIST_SUCCESS =  "CHAT_ONETOONE_LIST_SUCCESS"
export const CHAT_ONETOONE_LIST_FAIL =  "CHAT_ONETOONE_LIST_FAIL"
export const CHAT_ONETOONE_LIST_RESET =  "CHAT_ONETOONE_LIST_RESET"

export const CHAT_GROUP_CREATE_REQUEST =  "CHAT_GROUP_CREATE_REQUEST"
export const CHAT_GROUP_CREATE_SUCCESS =  "CHAT_GROUP_CREATE_SUCCESS"
export const CHAT_GROUP_CREATE_FAIL =  "CHAT_GROUP_CREATE_FAIL"
export const CHAT_GROUP_CREATE_RESET =  "CHAT_GROUP_CREATE_RESET"

export const CHAT_GROUP_LIST_REQUEST =  "CHAT_GROUP_LIST_REQUEST"
export const CHAT_GROUP_LIST_SUCCESS =  "CHAT_GROUP_LIST_SUCCESS"
export const CHAT_GROUP_LIST_FAIL =  "CHAT_GROUP_LIST_FAIL"

export const CHAT_GROUP_RENAME_REQUEST =  "CHAT_GROUP_RENAME_REQUEST"
export const CHAT_GROUP_RENAME_SUCCESS =  "CHAT_GROUP_RENAME_SUCCESS"
export const CHAT_GROUP_RENAME_FAIL =  "CHAT_GROUP_RENAME_FAIL"

export const CHAT_GROUP_ADDTO_REQUEST =  "CHAT_GROUP_ADDTO_REQUEST"
export const CHAT_GROUP_ADDTO_SUCCESS =  "CHAT_GROUP_ADDTO_SUCCESS"
export const CHAT_GROUP_ADDTO_FAIL =  "CHAT_GROUP_ADDTO_FAIL"

export const CHAT_GROUP_REMOVEFROM_REQUEST =  "CHAT_GROUP_REMOVEFROM_REQUEST"
export const CHAT_GROUP_REMOVEFROM_SUCCESS =  "CHAT_GROUP_REMOVEFROM_SUCCESS"
export const CHAT_GROUP_REMOVEFROM_FAIL =  "CHAT_GROUP_RENAME_FAIL"

