export const MESSAGE_ALL_LIST_REQUEST = "MESSAGE_ALL_LIST_REQUEST"
export const MESSAGE_ALL_LIST_SUCCESS = "MESSAGE_ALL_LIST_SUCCESS"
export const MESSAGE_ALL_LIST_FAIL = "MESSAGE_ALL_LIST_FAIL"
export const MESSAGE_ALL_LIST_RESET = "MESSAGE_ALL_LIST_RESET"

export const MESSAGE_SEND_REQUEST = "MESSAGE_SEND_REQUEST"
export const MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS"
export const MESSAGE_SEND_FAIL = "MESSAGE_SEND_FAIL"
export const MESSAGE_SEND_RESET = "MESSAGE_SEND_RESET"